### ISSUE TITLE
Use media query strings to set the viewport config object

### ISSUE THREAD

**Issue by christowiz** [ryanfitzer/ViewportJS#4]
In addition to setting the `width` and `height` arrays it would be nice to be able to directly use a media query string instead.

```js
var myViewports = viewport([
    {
        name: 'small',
        // width: [ 0, 480 ]
        query: '( min-width:0px ) and ( max-width:480px )'
    },
    {
        name: 'medium',
        // width: [ 481, 768 ]
        query: '( min-width:480px ) and ( max-width:767px )'
    },
    {
        name: 'large',
        // width: [ 769 ]
        query: '( min-width:769px )'
    }
]);
```

**Comment by ryanfitzer** [comment]
I think this would be pretty simple now that v2.0.0 only supports browsers that support the `MediaQueryList` API.

**Comment by christowiz** [comment]
This would also be an option to allow a JS object to assign the queries similar to https://github.com/akiran/json2mq

**Comment by ryanfitzer** [comment]
The more I think about this, the more I don't see it as a good idea. The configuration is very specific to viewport dimensions. Opening it up the possibilities supported by `json2mq` (or parsing a media query string) could be confusing as it supports media types and all [media features](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features), not just `width` and `height`.

**Comment by christowiz** [comment]
<sad face>

**Comment by ryanfitzer** [comment]
@christowiz What was the reason you originally wanted this feature?

**Comment by christowiz** [comment]
Because it would be cool and the MediaQueryList API uses queries natively so instead of having to build the query from the array ([L78](https://github.com/ryanfitzer/ViewportJS/blob/master/viewport.js#L78)) the lib can just consume it directly.

**Comment by ryanfitzer** [comment]
You're totally right. I think what confused me is your reference to `json2mq`. Your original request for supporting configuration with media query strings would be really simple (as I originally [commented](https://github.com/ryanfitzer/ViewportJS/issues/4#issuecomment-383622105)).

I'll reopen. Sorry for the confusion.

**Comment by ryanfitzer** [comment]
See the [v3 migration guide](../docs/migrating-to-3.0.0.md) for implementation.
